spring:
    application:
        name: hr-user
    datasource:
        password: ''
        url: jdbc:h2:mem:testdb
        username: sa
    h2:
        console:
            enabled: true
            path: /h2-console
    jpa:
        generate-ddl: true
        show-sql: true
        hibernate:
            format_sql: true
            ddl-auto: update
eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka
    instance:
        instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
server:
    port: ${PORT:0}